export { renderSceneToPng, renderWatermarkPng, COMPOSABLE_KINDS } from "./render-scene.ts";
export type { RenderSceneOpts, RenderedScene } from "./render-scene.ts";
export { renderHyperframeElementToPng, renderHyperframeElementToRgba } from "./render-hyperframe-tree.ts";
export type { HyperframeTreeRenderOpts, RenderedHyperframeFrame } from "./render-hyperframe-tree.ts";
export type { MotionClock } from "./hyperframe/motion.ts";
export { renderCaptionedFrame, drawCaptionOverlay } from "./render-caption.ts";
export { dimsFor, type Dims } from "./dims.ts";
export { probeImageInfo } from "./image-info.ts";
export type { ImageInfo } from "./image-info.ts";
export { THEME, canvasTheme, type CanvasTheme, type SemanticTheme } from "./theme.ts";
